services:
  kavita:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 768m
    ports:
      - "5000"
    volumes:
      - /var/lib/docker/volumes/lvdyq965xfop7zlq267odq0p_suwayomi-data/_data:/suwayomi-data:ro
      - kavita-config:/kavita/config
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.kavita-http.entryPoints=http"
      - "traefik.http.routers.kavita-http.middlewares=redirect-to-https"
      - "traefik.http.routers.kavita-http.rule=Host(`inkstream.stapulasolutions.com`) || Host(`library.stapulasolutions.com`)"
      - "traefik.http.routers.kavita-http.service=kavita-svc"
      - "traefik.http.routers.kavita-https.entryPoints=https"
      - "traefik.http.routers.kavita-https.middlewares=gzip"
      - "traefik.http.routers.kavita-https.rule=Host(`inkstream.stapulasolutions.com`) || Host(`library.stapulasolutions.com`)"
      - "traefik.http.routers.kavita-https.service=kavita-svc"
      - "traefik.http.routers.kavita-https.tls=true"
      - "traefik.http.routers.kavita-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.kavita-svc.loadbalancer.server.port=5000"

volumes:
  kavita-config:

networks:
  coolify:
    external: true
